source 'https://github.com/CocoaPods/Specs.git'

target 'DZSwipeViewController', :exclusive => true do
  pod "DZSwipeViewController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DZSwipeViewController", :path => "../"

  pod 'FBSnapshotTestCase'
end
